@DientesLimpios.API_HostAddress = http://localhost:5270/api/Consultorios

GET {{DientesLimpios.API_HostAddress}}/019F09DC-4A65-7005-B3CB-D7CB983CED2B
Accept: application/json

###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "nombre" : "Consultorio B"
}

###
PUT {{DientesLimpios.API_HostAddress}}/019F09DC-4A65-7005-B3CB-D7CB983CED2B
Content-Type: application/json

{
  "nombre" : "Consultorio B-Actualizado"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019f108f-e84b-7c34-a5e1-ef5d49cf5c61
Accept: applicaion/json
