@DientesLimpios.API_HostAddress = http://localhost:5270/api/Pacientes

//Retorna un paciente por Id
GET {{DientesLimpios.API_HostAddress}}/019f68d5-a4fa-7888-8879-206683c84a47
Accept: application/json

###Listado Paginado

GET {{DientesLimpios.API_HostAddress}}?pagina=2&registrosporpagina=2
Content-Type: application/json


###Crea un Paciente

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "nombre" : "Ismael Santes",
  "email" : "ismaelSantes@ejemplo.com"
}

###Retorna Todos los Pacientes

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json



###
PUT {{DientesLimpios.API_HostAddress}}/019f828f-df3c-740a-ab63-eed7babca209
Content-Type: application/json

{
  "nombre" : "Paciente Santes Actualizado",
  "email" : "SantesUpdated@ejemplo.com"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019f108f-e84b-7c34-a5e1-ef5d49cf5c61
Accept: applicaion/json
